version: "3"
services:
  java:
    build: ./api_java
    ports:
      - 8080:8080

  java_multi:
    build: 
      context: ./api_java
      dockerfile: ./Dockerfile_multi
    ports:
      - 8080:8080

  python:
    build: ./python_fastapi
    ports:
      - 8000:8000
