version: "3"
services:
  java:
    build: ./api_java
    ports:
      - 8080:8080

  java_multi:
    build: 
      context: ./api_java
      dockerfile: ./Dockerfile_multi
    ports:
      - 8081:8080

  python:
    build: ./python_fastapi
    ports:
      - 8000:8000

  consul:
    image: consul:1.15.4
    ports:
      - 8500:8500
    volumes:
      - ./data:/consul/config
  
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - 127.0.0.1:3001:3001
    volumes:
      - ./kuma_data:/app/data
