FROM eclipse-temurin:17.0.8_7-jdk-jammy as step_01
WORKDIR /app
COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .
COPY src src
RUN --mount=type=cache,target=/root/.m2,rw ./mvnw -B package

FROM tomcat:10.1.13-jre17-temurin-jammy
WORKDIR /app
COPY --from=step_01 /app/target/*.war /usr/local/tomcat/webapps/demo.war
EXPOSE 8080